// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { emitPermissionErrorEvent, extractSupabaseTable, parsePermissionError } from '@/lib/permissionErrors';

const SUPABASE_URL = "https://umybjmuzbxfxdtbumgma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVteWJqbXV6YnhmeGR0YnVtZ21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTY3MzUsImV4cCI6MjA2MzEzMjczNX0.ODvajzrDaKfqDOzXGNwEr4CaAYRgPY38e-vYeVTS5OY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: async (input, init) => {
      const response = await fetch(input, init);

      if (response.ok) return response;

      const requestUrl = input instanceof Request ? input.url : String(input);
      if (!requestUrl.includes('/rest/v1/')) return response;

      try {
        const payload = await response.clone().json();
        const table = extractSupabaseTable(requestUrl);
        const permissionError = parsePermissionError(payload, table);

        if (permissionError) {
          emitPermissionErrorEvent(permissionError);
        }
      } catch {
        return response;
      }

      return response;
    },
  },
});